DROP TABLE IF EXISTS my_table;

CREATE TABLE my_table (
  item TEXT,
  id_netux TEXT,
  criterio_calificacion TEXT,
  nombre_equipo TEXT,
  estado_informe TEXT,
  codigo_certificado TEXT,
  marca TEXT,
  serie TEXT,
  descripcion TEXT,
  iq TEXT,
  oq TEXT,
  pq TEXT,
  cal TEXT,
  centro_costo TEXT,
  area TEXT,
  ubicacion_fisica TEXT,
  proveedor TEXT,
  enero TEXT,
  febrero TEXT,
  marzo TEXT,
  abril TEXT,
  mayo TEXT,
  junio TEXT,
  julio TEXT,
  agosto TEXT,
  septiembre TEXT,
  octubre TEXT,
  noviembre TEXT,
  diciembre TEXT,
  fecha TEXT,
  dias_vigencia_certificado TEXT,
  torre TEXT,
  pendientes TEXT,
  p_iq TEXT,
  p_oq TEXT,
  p_pq TEXT,
  p_cal TEXT,
  precio_unitario TEXT
);

